import { Command } from 'commander';
import { DatabaseClient, schema } from '@codeatlas/database';
import { RiskEngine } from '@codeatlas/risk-engine';
import { GraphEngine } from '@codeatlas/analyzer';
import { isNotNull, eq } from 'drizzle-orm';
import { generateArchitectureSummary, getAiConfig } from '@codeatlas/ai';
import * as fs from 'fs';
import * as path from 'path';
import pc from 'picocolors';

export const reportCommand = new Command('report')
  .description('Generate a Markdown report of the latest analysis')
  .option('-o, --output <string>', 'Output file path', 'codeatlas-report.md')
  .action(async (options) => {
    try {
      const dbClient = new DatabaseClient('codeatlas.db');

      const repo = dbClient.db.select().from(schema.repositories).get();
      if (!repo) {
        console.error(pc.red('No repository found. Please run "codeatlas analyze" first.'));
        process.exit(1);
      }

      const latestRun = dbClient.db.select().from(schema.analysisRuns).orderBy(schema.analysisRuns.startedAt).limit(1).get();
      if (!latestRun) {
        console.error(pc.red('No completed analysis run found. Please run "codeatlas analyze".'));
        process.exit(1);
      }

      const commit = dbClient.db.select().from(schema.commits).where(eq(schema.commits.repositoryId, repo.id)).get();

      const files = dbClient.db.select().from(schema.files).all();
      const imports = dbClient.db
        .select()
        .from(schema.imports)
        .where(isNotNull(schema.imports.resolvedFileId))
        .all();
      const symbols = dbClient.db.select().from(schema.symbols).all();

      const graph = new GraphEngine();
      files.forEach((f) => graph.addNode(f.id));
      imports.forEach((i) => graph.addEdge(i.fileId, i.resolvedFileId!));

      const riskEngine = new RiskEngine();

      const cycles = graph.getCircularDependencies();

      const riskEvaluations = files.map((f) => {
        const fanIn = graph.getDirectDependents(f.id).length;
        const fanOut = graph.getDirectDependencies(f.id).length;
        const depth = graph.getDepth(f.id);
        const hasCircularDependency = cycles.some((cycle) => cycle.includes(f.id));

        const isTestFile = (p: string) => /\.(test|spec)\.[jt]sx?$/.test(p) || /__tests__/.test(p);
        const dependents = graph
          .getDirectDependents(f.id)
          .map((id) => files.find((file) => file.id === id));
        const hasTests = dependents.some((dep) => dep && isTestFile(dep.path));

        const evaluation = riskEngine.evaluate({
          fanIn,
          fanOut,
          depth,
          lines: f.lines,
          hasTests,
          hasCircularDependency,
        });

        return { file: f, risk: evaluation, fanIn, fanOut, hasCircularDependency };
      });

      // Sort by risk score descending
      riskEvaluations.sort((a, b) => b.risk.score - a.risk.score);

      const highRiskFiles = riskEvaluations.filter((r) => r.risk.level === 'High Risk');

      console.log(pc.blue('Generating architecture summary...'));
      let architectureSection = '## Architecture Summary\n\n*Running locally without AI. Deterministic metrics only.*\n';
      
      const aiConfig = getAiConfig();
      if (aiConfig.provider || aiConfig.baseUrl) {
        const rawContext = files.slice(0, 300).map(f => f.path).join('\\n');
        const aiSummary = await generateArchitectureSummary(dbClient, rawContext, repo.id, latestRun.commitId);
        if (aiSummary) {
          architectureSection = `## Architecture Summary (AI Generated)
          
**Purpose**: ${aiSummary.purpose}

**Architecture Style**: ${aiSummary.architectureStyle}

**Testing Structure**: ${aiSummary.testingStructure}

**Major Modules**:
${aiSummary.majorModules.map((m: string) => `- ${m}`).join('\n')}

**Important Dependencies**:
${aiSummary.importantDependencies.map((d: string) => `- ${d}`).join('\n')}

**Entry Points**:
${aiSummary.entryPoints.map((e: string) => `- ${e}`).join('\n')}

**High-Risk Areas Highlighted by AI**:
${aiSummary.highRiskAreas.map((h: string) => `- ${h}`).join('\n')}
`;
        }
      }

      const markdown = `
# CodeAtlas Analysis Report
**Repository**: ${repo.name}
**Commit Hash**: ${commit ? commit.hash : 'Unknown'}
**Generated on**: ${new Date().toLocaleString()}

> [!NOTE]
> This report was generated by CodeAtlas using static AST analysis.

## Overview
- **Total Files Analyzed**: ${files.length}
- **Total Symbols Discovered**: ${symbols.length}
- **Total Dependencies**: ${imports.length}
- **High Risk Files**: ${highRiskFiles.length}
- **Circular Dependency Cycles**: ${cycles.length}

${architectureSection}

## Top Architectural Risks

${highRiskFiles.length === 0 ? '_No high-risk files detected._' : ''}
${highRiskFiles
  .map(
    (r) => `### \`${r.file.path}\`
- **Risk Score**: ${r.risk.score} (${r.risk.level})
- **Fan-in**: ${r.fanIn} | **Fan-out**: ${r.fanOut}
- **Factors**:
${r.risk.factors.map((f) => `  - **${f.name}** (+${f.contribution}): ${f.description}`).join('\n')}
`,
  )
  .join('\n')}

## Dependency Cycles

${cycles.length === 0 ? '_No dependency cycles detected._' : ''}
${cycles.map((cycle, index) => {
  const cyclePaths = cycle.map(id => files.find(f => f.id === id)?.path || id);
  return `**Cycle #${index + 1}**\n\`\`\`\n${cyclePaths.join(' -> ')}\n\`\`\``;
}).join('\n\n')}

## All Files

| File | Lines | Fan-in | Fan-out | Risk Level |
|---|---|---|---|---|
${riskEvaluations.map((r) => `| \`${r.file.path}\` | ${r.file.lines} | ${r.fanIn} | ${r.fanOut} | ${r.risk.level} |`).join('\n')}

      `;

      const outputPath = path.resolve(process.cwd(), options.output);
      fs.writeFileSync(outputPath, markdown.trim());

      console.log(pc.green(`Report successfully generated at: ${outputPath}`));
    } catch (error: unknown) {
      if (error instanceof Error) {
        console.error(pc.red(`\nError: ${error.message}`));
      } else {
        console.error(pc.red(`\nError: Unknown error`));
      }
      process.exit(1);
    }
  });
