packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  esbuild: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-python: set this to true or false
  tree-sitter-typescript: set this to true or false
